[build]
  publish = "."
  # No build command needed for static HTML

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling
[[redirects]]
  from = "/contact"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/thank-you.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 